### ISSUE TITLE
Token refresh mechanism does not work properly

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#137]
When connections are active for a long time, it seems the token refresh mechanism for the session is not working properly. Here is the error produced:

```
2022-09-08 09:55:32,339 : ERROR : aperturedb.ParallelQuery : 155 : 0
Traceback (most recent call last):
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/ParallelQuery.py", line 153, in worker
    self.do_batch(db, generator[batch_start:batch_end])
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/ParallelQuery.py", line 83, in do_batch
    r, b = db.query(q, blobs)
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/Connector.py", line 284, in query
    self._check_session_status()
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/Connector.py", line 167, in _check_session_status
    self._refresh_token()
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/Connector.py", line 179, in _refresh_token
    session_info = response[0]["RefreshToken"]
KeyError: 0
2022-09-08 09:55:32,344 : ERROR : aperturedb.ParallelQuery : 155 : 0
Traceback (most recent call last):
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/ParallelQuery.py", line 153, in worker
    self.do_batch(db, generator[batch_start:batch_end])
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/ParallelQuery.py", line 83, in do_batch
    r, b = db.query(q, blobs)
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/Connector.py", line 284, in query
    self._check_session_status()
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/Connector.py", line 167, in _check_session_status
    self._refresh_token()
  File "/home/luis_remis/.local/lib/python3.7/site-packages/aperturedb/Connector.py", line 179, in _refresh_token
    session_info = response[0]["RefreshToken"]
KeyError: 0
```

**Comment by gsaluja9** [comment]
This has been addressed in release 0.3.2
