### ISSUE TITLE
ParallelQuery not handling error in some situations

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#238]
When db returns an error:
```
{
  'info': 'Failed opening file for writing :db/objects/0000/1742/0000-1742-000000-109980.png', 
  'status': -1
}
```
Python package fails to capture the error.

```
2023-06-07 21:21:11,982 : ERROR : aperturedb.ParallelQuery : 139992848397888 : 226 : 'returned'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ParallelQuery.py", line 224, in worker
    self.do_batch(db, generator[batch_start:batch_end])
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ParallelQuery.py", line 179, in do_batch
    result, r, b = execute_batch(
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ParallelQuery.py", line 56, in execute_batch
    count = resp[k]["returned"]
KeyError: 'returned'
```

Here is the [complete log file](https://s3.console.aws.amazon.com/s3/object/adb-performance-evaluation?region=us-west-2&prefix=2023-06-07/coco-val/1686172953_ci_bench_dsm-s3_2b/error.2023-06-07T20%3A31%3A49.386039.log).

**Comment by gsaluja9** [comment]
@luisremis can you verify and close this?
