### ISSUE TITLE
Loader stats showing NaN when error occur

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#244]
When there are errors, it seems there is a problem accounting for 

    Overall insertion throughput (element/s): NaN

See full status below:

```
remis@server:~/ad/apps/demos/yfcc100m$ cat ingest.log
[
    {
        "GetStatus": {
            "info": "OK",
            "status": 0,
            "system": "ApertureDB",
            "version": "0.15.4"
        }
    }
]
Loading images...
Progress: 100.00% - ETA(s): 0.00
============ ApertureDB Loader Stats ============
Total time (s): 17113.949018716812
Total queries executed: 200051
Avg Query time (s): 9.672629570466526
Query time std: 3.6180601510894435
Avg Query Throughput (q/s): 13.23321637280754
Overall insertion throughput (element/s): NaN
Total errors encountered: 2318
Errors (%): 1.158704530344762
Total inserted elements: 988412
Total successful commands: 988412
=================================================
Done.
```

**Comment by luisremis** [comment]
Here is another instance, also showing Errors: 103%

```
Progress: 99.36% - ETA(s): 35.02
Progress: 99.68% - ETA(s): 17.78
Progress: 100.00% - ETA(s): 0.00
============ ApertureDB Loader Stats ============
Total time (s): 8469.170392513275
Total queries executed: 3050
Avg Query time (s): 6.925222988441342
Query time std: 25.208140901397304
Avg Query Throughput (q/s): 2.3103949182149175
Overall insertion throughput (element/s): NaN
Total errors encountered: 3148
Errors (%): 103.21311475409836
Total inserted elements: 370032
Total successful commands: 370032
=================================================
```

**Comment by luisremis** [comment]
it looks it some of the error counting issues continue. Also NaNs:

This is on 0.4.15

```
│ ============ ApertureDB Loader Stats ============                                                                                                                      │
│ Total time (s): 5806.698908090591                                                                                                                                      │
│ Total queries executed: 151                                                                                                                                            │
│ Avg Query time (s): 213.69277925049232                                                                                                                                 │
│ Query time std: 392.6994673465528                                                                                                                                      │
│ Avg Query Throughput (q/s): 0.07487384485389971                                                                                                                        │
│ Overall insertion throughput (element/s): NaN                                                                                                                          │
│ Total errors encountered: 1546                                                                                                                                         │
│ Errors (%): 1023.841059602649                                                                                                                                          │
│ Total inserted elements: 29136                                                                                                                                         │
│ Total successful commands: 29136                                                                                                                                       │
│ =================================================
```

**Comment by luisremis** [comment]
Here is another instance on 0.4.16:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ParallelQuery.py", line 237, in worker
    self.do_batch(db, generator[batch_start:batch_end])
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ParallelQuery.py", line 185, in do_batch
    result, r, b = execute_batch(
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ParallelQuery.py", line 32, in execute_batch
    r, b = db.query(q, blobs)
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/Connector.py", line 352, in query
    raise ConnectionError("ApertureDB disconnected")
ConnectionError: ApertureDB disconnected
============ ApertureDB Parallel Query Stats ============
Total time (s): 2549.3945622444153
Total queries executed: 1572295
Avg Query time (s): 0.0038538377592425557
Query time std: 0.009322201831475647
Avg Query Throughput (q/s): 8303.41130039926
Overall insertion throughput (query/s): NaN
Total errors encountered: 8427724
Errors (%): 536.0141703687921
=========================================================
```
