### ISSUE TITLE
Uncaught exepction on Connector.py

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#246]
When running tests:

FAILED test_Data.py::TestEntityLoader::test_LoaderDescriptorsImages[TCP-with_dask] - assert (8000 - 7986) == 0

```
[#######                                 ] | 19% Completed |  1.0s2023-06-21 15:36:09,073 : ERROR : aperturedb.Connector : 139697611798080 : 257 : Error connecting to server: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:997)
Exception in thread Thread-7 (worker):
Traceback (most recent call last):
  File "/home/remis/ad/py-aperturedb/aperturedb/Connector.py", line 254, in _connect
    self.conn = self.context.wrap_socket(self.conn)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
[############                            ] | 31% Completed |  1.3s    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/remis/ad/py-aperturedb/aperturedb/ParallelQuery.py", line 211, in worker
    db = self.db.create_new_connection()
  File "/home/remis/ad/py-aperturedb/aperturedb/Connector.py", line 367, in create_new_connection
    return type(self)(
  File "/home/remis/ad/py-aperturedb/aperturedb/Connector.py", line 102, in __init__
    self._connect()
  File "/home/remis/ad/py-aperturedb/aperturedb/Connector.py", line 260, in _connect
    raise ConnectionError("Failed to connect to ApertureDB")
ConnectionError: Failed to connect to ApertureDB
```

**Comment by gsaluja9** [comment]
@luisremis This was observed in versions prior to 0.15.7 . If you still observe this, please provide the version details .

**Comment by luisremis** [comment]
ok, if the issue is fixed in newer versions, I will just close this.
