### ISSUE TITLE
Bug on ParallelLoader when running with dry_run=True

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#250]
```
remis@server:~/ad/apps/demos/yfcc100m$ cat error.log
Traceback (most recent call last):
  File "/home/remis/ad/apps/demos/yfcc100m/load_yfcc.py", line 64, in <module>
    main(args)
  File "/home/remis/ad/apps/demos/yfcc100m/load_yfcc.py", line 30, in main
    loader.ingest(img_data, batchsize=params.batchsize,
  File "/home/remis/ad/py-aperturedb/aperturedb/ParallelLoader.py", line 75, in ingest
    self.query(generator, batchsize, numthreads, stats)
  File "/home/remis/ad/py-aperturedb/aperturedb/ParallelQuery.py", line 297, in query
    self.run(generator, batchsize, numthreads, stats)
  File "/home/remis/ad/py-aperturedb/aperturedb/Parallelizer.py", line 79, in run
    self.print_stats()
  File "/home/remis/ad/py-aperturedb/aperturedb/ParallelLoader.py", line 98, in print_stats
    suceeded_queries = sum([stat["suceeded_queries"]
  File "/home/remis/ad/py-aperturedb/aperturedb/ParallelLoader.py", line 98, in <listcomp>
    suceeded_queries = sum([stat["suceeded_queries"]
KeyError: 'suceeded_queries'
```

**Comment by gsaluja9** [comment]
Is this still a problem ?

**Comment by luisremis** [comment]
I don't remember seeing this in a while. @drewaogle may know.
