### ISSUE TITLE
aperturedb fails if cv2 package is not installed

### ISSUE THREAD

**Issue by luisremis** [aperture-data/aperturedb-python#351]
All watchdog needs is to use `Utils.create_connector()` function. 

`pip3 install aperturedb==version` is not enough for this. 

```
remis@server:~/ad/aperturedb$ docker run  -it -e DB_HOST=localhost aperturedata/app-watchdog:vci_fix_watchdog_dbconfig
Traceback (most recent call last):
  File "/usr/local/bin/adb", line 5, in <module>
    from aperturedb.cli.adb import app
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/cli/adb.py", line 3, in <module>
    from aperturedb.cli import configure, ingest, utilities, transact
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/cli/ingest.py", line 9, in <module>
    from aperturedb.ImageDataCSV import ImageDataCSV
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ImageDataCSV.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

The quick solution is to do:
```
pip3 install aperturedb[complete]==version
```

I think we should not need `complete` for the most basic task of creating a single connection.

**Comment by luisremis** [comment]
[complete] is not enough, we need the extra steps to install libGL.so (usually installed through opencv): 

```
remis@server:~/ad/aperturedb$ docker run  -it -e DB_HOST=localhost aperturedata/app-watchdog:vci_fix_watchdog_dbconfig
Traceback (most recent call last):
  File "/usr/local/bin/adb", line 5, in <module>
    from aperturedb.cli.adb import app
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/cli/adb.py", line 3, in <module>
    from aperturedb.cli import configure, ingest, utilities, transact
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/cli/ingest.py", line 9, in <module>
    from aperturedb.ImageDataCSV import ImageDataCSV
  File "/usr/local/lib/python3.10/dist-packages/aperturedb/ImageDataCSV.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

this should not be needed for a basic connection.
