### ISSUE TITLE
SDK trial on Mac

### ISSUE THREAD

**Issue by vishakha041** [aperture-data/aperturedb-python#467]
Drew’s tagged version worked for ApertureDB server.

1. Adb was quite slow weirdly. 3 sec to load. Config ls - looks like we load unnecessary packages for certain commands like config ls. After caching - 1.4s  --> PYTHONPROFILEIMPORTTIME=1 adb config ls
2. If you run adb ingest without config - it just hung.
3. We print admin password in stack trace
4. If you create a config with same name twice - it just replaces existing config. Not sure that’s intentional.
5. Adb ingest doesn’t work due to the port forwarding stuff. Adb UI connected.
6. Our error stack for python is so long it’s too much. Is ipython slowing stuff too much ? Hurting user experience

**Comment by vishakha041** [comment]
(adb) --($:~/.../adb/slim-stanford-car-dataset)---$ adb utils execute summary
2024-08-23 11:13:31,493 : ERROR : aperturedb.Connector : 8653999936 : 330 : Error connecting to server: [Errno 54] Connection reset by peer [127.0.0.1:456 as admin using TCP with SSL=True]
Traceback (most recent call last):
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 306, in _connect
    response = self._recv_msg()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 195, in _recv_msg
    recv_len = self.conn.recv(4)  # get message size
ConnectionResetError: [Errno 54] Connection reset by peer
Stack (most recent call last):
  File "/Users/rcledat/mambaforge/envs/adb/bin/adb", line 8, in <module>
    sys.exit(app())
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/core.py", line 723, in main
    return _main(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/cli/utilities.py", line 44, in execute
    available_commands[command]()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Utils.py", line 323, in summary
    r = self.get_schema()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Utils.py", line 188, in get_schema
    res, _ = self.connector.query(query)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 460, in query
    self.authenticate(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 171, in authenticate
    self._authenticate(user, password, token)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 229, in _authenticate
    response, _ = self._query(query)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 426, in _query
    self.connect(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 347, in connect
    self._connect()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 330, in _connect
    logger.error(
2024-08-23 11:13:31,495 : ERROR : aperturedb.Connector : 8653999936 : 349 : Error connecting to server: [127.0.0.1:456 as admin using TCP with SSL=True]
Will retry in 1 seconds.
Traceback (most recent call last):
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 347, in connect
    self._connect()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 306, in _connect
    response = self._recv_msg()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 195, in _recv_msg
    recv_len = self.conn.recv(4)  # get message size
ConnectionResetError: [Errno 54] Connection reset by peer
Stack (most recent call last):
  File "/Users/rcledat/mambaforge/envs/adb/bin/adb", line 8, in <module>
    sys.exit(app())
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/core.py", line 723, in main
    return _main(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/cli/utilities.py", line 44, in execute
    available_commands[command]()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Utils.py", line 323, in summary
    r = self.get_schema()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Utils.py", line 188, in get_schema
    res, _ = self.connector.query(query)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 460, in query
    self.authenticate(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 171, in authenticate
    self._authenticate(user, password, token)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 229, in _authenticate
    response, _ = self._query(query)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 426, in _query
    self.connect(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 349, in connect
    logger.error(
2024-08-23 11:13:32,496 : ERROR : aperturedb.Connector : 8653999936 : 407 : [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 380, in _query
    if self._send_msg(data):
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 191, in _send_msg
    x = self.conn.send(sent_len + data)
OSError: [Errno 9] Bad file descriptor
2024-08-23 11:13:32,501 : ERROR : aperturedb.Connector : 8653999936 : 330 : Error connecting to server: [Errno 54] Connection reset by peer [127.0.0.1:456 as admin using TCP with SSL=True]
Traceback (most recent call last):
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 306, in _connect
    response = self._recv_msg()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 195, in _recv_msg
    recv_len = self.conn.recv(4)  # get message size
ConnectionResetError: [Errno 54] Connection reset by peer
Stack (most recent call last):
  File "/Users/rcledat/mambaforge/envs/adb/bin/adb", line 8, in <module>
    sys.exit(app())
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/core.py", line 723, in main
    return _main(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rcledat/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/cli/utilities.py", line 44, in execute
    available_commands[command]()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Utils.py", line 323, in summary
    r = self.get_schema()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Utils.py", line 188, in get_schema
    res, _ = self.connector.query(query)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 460, in query
    self.authenticate(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 171, in authenticate
    self._authenticate(user, password, token)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 229, in _authenticate
    response, _ = self._query(query)
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 426, in _query
    self.connect(
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 347, in connect
    self._connect()
  File "/Users/rcledat/mambaforge/envs/adb/lib/python3.10/site-packages/aperturedb/Connector.py", line 330, in _connect
    logger.error(
2024-08-23 11:13:32,502 : ERROR : aperturedb.Connector : 8653999936 : 349 : Error connecting to server: [127.0.0.1:456 as admin using TCP with SSL=True]
Will retry in 1 seconds.

**Comment by vishakha041** [comment]
(adb) --($:~/.../adb/slim-stanford-car-dataset)---$ adb config ls
[11:14:59] Available configurations:                                                                                                                                                                                                                                                             configure.py:96
           {'global': {'test': [127.0.0.1:456 as admin using TCP with SSL=True]}, 'active': 'test'}

**Comment by gsaluja9** [comment]
services:

aperturedb:
image: drewaogle/aperturedb-standalone:0.17.17.1
restart: always
privileged: true
volumes: # Map ApertureDB storage and logs into local directory
- ./aperturedb/db:/aperturedb/db
- ./aperturedb/logs:/aperturedb/logs
ports:
- 456:55555 # HOST_PORT:CONTAINER_PORT

webui:
image: aperturedata/aperturedb-webui
ports:
- 8080:80 # HOST_PORT:CONTAINER_PORT
restart: always
depends_on:
- aperturedb
environment:
- APP_PRIVATE_VDMS_SERVER_ADDR=aperturedb
- APP_PRIVATE_VDMS_SERVER_PORT=55555

**Comment by gsaluja9** [comment]
For point #2 , there was no socket timeout set before calling connect. Putting that to a reasonable value mitigates this scenario.

**Comment by gsaluja9** [comment]
4 it bails out unless an extra flag is used.

**Comment by gsaluja9** [comment]
@vishakha041  @drewaogle . The develop branch has these fixes. Time to try let me know how the experience turns out.

**Comment by gsaluja9** [comment]
This has been released now, @vishakha041 , can you retry?

**Comment by drewaogle** [comment]
yeah this should be good. We still need to figure out the pip issue to put the community builder in athena though.

**Comment by gsaluja9** [comment]
1. Remove stack trace from console. 
2. Add a link to troubleshooting page.
3. But notify user of its presence in error file. (on console or troubleshooting page)
